package org.omnypay.mobileapp.oauth;
/* @author Susil Rayaguru
 *  
 */
public enum FilterConstant {

REQUEST_DENIED, REQUEST_ALLOWED, REQUEST_FOR_LOGIN_SUCCESS,	
REQUEST_FOR_LOGIN_FAILED,ACCESS_TOKEN_NOT_FOUND,TOKEN_EXPIRED,
INVALID_ACCESS_TOKEN,INVALID_USER_CREDENTIAL;
}
